version: '3'

services:
    app:
        container_name: app-node
        build:
            context: .
            dockerfile: ./docker/nodejs.dockerfile
        image: app-node
        volumes:
          - .:/usr/sdfcli
          - /usr/sdfcli/node_modules
        environment:
          - npm_config_unsafe_perm=true
        ports:
          - "3000:3000"